var g_loc = {
    "LOCALE": "en",
    "LOC_SEP": "September",
    "LOC_OCT": "October",
    "LOC_NOV": "November",
    "LOC_DEC": "December",
    "LOC_JAN": "January",
    "LOC_FEB": "February",
    "LOC_MAR": "March",
    "LOC_APR": "April",
    "LOC_MAY": "May",
    "LOC_JUN": "June",
    "LOC_JUL": "July",
    "LOC_AUG": "August",
    "LOC_INFO": "Node info",
    "LOC_GINFO": "Graph info",
    "LOC_NODES": "Nodes",
    "LOC_EDGES": "Edges",
    "LOC_SETTINGS": "Settings",
    "LOC_FILTERS": "Filters",
    "LOC_GROUPS": "Clusters",
    "LOC_SELSTUB": "Click on the node to get info about it",
    "LOC_EDGETHRESHOLD": "All edges:",
    "LOC_NODETHRESHOLD": "All nodes:",
    "LOC_PASSIVETEXTALPHA": "Unselected nodes lightness:",
    "LOC_PASSIVEEDGEALPHA": "Unselected edges lightness:",
    "LOC_NODEFONT": "Nodes font size:",
    "LOC_RINGFONT": "Ring scale font size:",
    "LOC_APPLY": "Apply",
    "LOC_ALL": "∀",
    "LOC_NONE": "∅",
    "LOC_VISIBLE": "Visible",
    "LOC_SELECTED": "Selected",
    "LOC_CHANGE": "Change",
    "LOC_GROUP": "Cluster",
    "LOC_COLOR": "Color",
    "LOC_ENTERGROUP": "Enter cluster",
    "LOC_LEAVEGROUP": "Leave cluster",
    "LOC_LINKEDNODES": "Linked nodes:",
    "LOC_STATSTUB": "Click on the pie sector to get info about corresponding cluster",
    "LOC_STATCAPTION": "Clusters statistics (number of clusters: ",
    "LOC_MALE": "male",
    "LOC_FEMALE": "female",
    "LOC_EDUCATION_MIDDLE": "secondary education",
    "LOC_EDUCATION_HIGH": "higher education",
    "LOC_NODE_DATA": "Node data",
    "LOC_FIT_TO_SCREEN": "Fit to screen",
    "LOC_SORT_BY_RING": "Sort",
    "LOC_CALC_MODULARITY": "Modularity",
    "LOC_RING_FILTER_ADD": "Add filter",
    "LOC_RING_FILTER_ARCS_GROUP": "Filter arcs",
    "LOC_RING_FILTER_ARCS_GROUP_SINGLE": "Single end (Shift+LMB)",
    "LOC_RING_FILTER_ARCS_GROUP_BOTH": "Both ends (Alt+LMB)",
    "LOC_RING_PAINT_NODES": "Paint nodes",
    "LOC_FINDSTRING": "Find by string",
    "LOC_FINDREGEXP": "Find by regexp",
    "LOC_NOT": "Not",
    "LOC_TREE": "Tree",
    "LOC_SAVE_GRAPH": "Export graph",
    "LOC_HELP": "Get Help",
    "LOC_HELPLOC": "/storage/GraphHelp",
    "LOC_GRAPHSTAT": "Graph statistics:",
    "LOC_SUMWEIGHT": "∑ weight =",
    "LOC_CALCULATOR": "Calculator",
    "LOC_ADDOPERAND": "Add Operand",
    "LOC_OPSUM": "Sum",
    "LOC_OPUNION": "Union",
    "LOC_OPDIFF": "Difference",
    "LOC_OPSYMDIFF": "Symmetric Difference",
    "LOC_OPINTERSECT": "Intersection",
    "LOC_CALCULATE": "Calculate",
    "LOC_CLEANCALC": "Clean",
    "LOC_STATECALCULATED": "Current state was calculated. Click to return to previous one.",
    "LOC_FILTER_SET": "Filter set:",
    "LOC_ADD_FILTER_SET": "+",
    "LOC_REM_FILTER_SET": "–",
    "LOC_SAVE_FILTER_SET": "Save to File",
    "LOC_FILTER_SET_AVAILABLE": "Avaliable sets: ",
    "LOC_EDGE_EDIT": "Edge edit mode",
    "LOC_CREATE_DIRECTED_EDGES": "Create directed edges",
};
