#!/usr/bin/env python3

CUTOFF_SETTING_THRESHOLD = 'Threshold'

CUTOFF_INPUT_VALUE = 'Value'
CUTOFF_OUTPUT_MARKER = 'Marker'

if MODE == 'INITIALIZATION':
    pass
else:
    OUTPUT[CUTOFF_OUTPUT_MARKER] = int(INPUT[CUTOFF_INPUT_VALUE] > SETTINGS_VAL[CUTOFF_SETTING_THRESHOLD])

PROCESS()
