#!/usr/bin/env python3

CONVERTER_INPUT_MNE_EEG = ''
CONVERTER_INPUT_MODE = ''

CONVERTER_OUTPUT_LABEL = ''
CONVERTER_OUTPUT_DATA = ''

CONVERTER_MODE_ANNOT = 0
CONVERTER_MODE_DC_A = 1

raw = INPUT[CONVERTER_INPUT_MNE_EEG]
mode = int(SETTINGS_VAL[CONVERTER_SETTING_MODE])

data = None
label = None

OUTPUT[CONVERTER_OUTPUT_LABEL] = label
OUTPUT[CONVERTER_OUTPUT_DATA] = data
