#!/usr/bin/env python3

STRINGIFY_INPUT_VALUE = 'Numeric Value'
STRINGIFY_OUTPUT_VALUE = 'String Value'

if MODE == 'INITIALIZATION':
    pass
else:
    OUTPUT[STRINGIFY_OUTPUT_VALUE] = str(INPUT[STRINGIFY_INPUT_VALUE])

PROCESS()
