var g_fsgraph_loc = {
    "en": {
        "#control": "Control",
        "#node_info": "Node info",
        "#node_list": "Node list",
        "#settings": "Settings",
        "#stats": "Stats",
        "#pause_resume": "Pause/resume layout",
        "#appearance": "Appearance",
        "#layout": "Layout",
        "#node_list_hint": "Click on list entry to center screen on specific node",
        "#hide_all_nodes": "Hide all",
        "#show_non_filtered": "Show all non-filtered",
        "#node_size_diap": "Node size diap",
        "#edge_size_diap": "Edge size diap",
        "#change_name": "Change",
        "#incoming_nodes": "Incoming links from",
        "#outcoming_nodes": "Outgoing links to",
        "#font": "Font",
        "#font_size": "Font size",
        "#apply": "Apply",
        "#layout_settigns": {
            "#springLength" : "Spring length",
            "#springCoeff": 'Spring coeff',
            "#edgeWeightInfluence": "Edge weight influence",
            "#outboundAttractionDistribution": "Outbound attraction distribution",
            "#linLogMode": "Lin-Log mode",
            "#barnesHutOptimize": "Barnes-Hut optimize"
        },
        "#node_types": {
            "circle": "Circle",
            "romb": "Rombus",
            "triang": "Triangle"
        },
        "#for_group": "For group",
        "#state_hint": "Show nodes with weight within specified range",
        "#fit_to_screen": "Fit to screen",
        "#cancel": "Cancel",
        "#precalc_layout": "Precalculating layout...",
        "#metric_diameter": "Diameter:",
        "#metric_degree": "Degree (average):",
        "#metric_density": "Density:",
        "#node_color": "Node color: ",
        "#node_type": "Node type: ",
        "#node_alpha": "Node alpha",
        "#edge_alpha": "Edge alpha",
        "#border_visible": "Show label border:",
		"LOC_BORDER_SIZE_TEXT": "Set border width",
		'#label_layout_strategy': "Label's layout strategy",
		'#around_vertex_strategy': "around vertex",
		'#inside_vertex_strategy': "inside vertex"
    },
    "ru": {
		"#CircleLayout" : "Круговая укладка",
		"#FruchtermanReingoldLayout" : "Укладка Фрухтермана-Рейнгольда",
		"#optimal_vertex_distance_text": "Оптимальное расстояние между вершинами",
		"#iterations_count_text": "Количество итераций укладки",
		"#is_bounding_text" : "Ограничить граф?",
		"#use_cluster_splitting_text": "Укладывать с учетом кластеров?",
		"#R_text": "Радиус",
		
		"#node_info_tab": "О Вершине",
		"#node_list_tab": "Вершины",
		"#links_tab": "Дуги",
		"#settings_tab": "Настройки",
		"#filters_tab": "Фильтры",
		"#calculator_tab": "Калькулятор",
		"#clusters_info_tab": "Кластеры",
		"#about_graph_tab": "О графе",
		"#metrics": "Метрики",
		"#save_as_png": "Сохранить как png",
		"#always_show_labels": "Показывать все заголовки вершин",
		"#always_show_weights": "Показывать все веса дуг",	
		"#out_links_text": "Исходящие дуги",
		"#in_links_text": "Входящие дуги",
		"#sort_alphabetically_text": "Сортировка по алфавиту",
		"#sort_by_weight_text": "Сортировка по весу",
		"#sort_asc": "↑",
		"#sort_desc": "↓",
		"#no_sort": "~",

		"#groups_count": "Количество кластеров",
		"#nodes_count": "Количество вершин",
		"#links_count": "Количество дуг",
		"LOC_BORDER_SIZE_TEXT": "Толщина границ",
		'#label_layout_strategy': "Стратегия укладки заголовков вершин",
		'#around_vertex_strategy': "Вокруг вершины",
		'#inside_vertex_strategy': "Внутри вершины",
		'#links_visibility_text': "Видимость дуг",
		
		"LOC_NO_GRAPH": "Данные графа отсутствуют",
		"LOCALE": "ru",
		"LOC_SEP": "Сентябрь",
		"LOC_OCT": "Октябрь",
		"LOC_NOV": "Ноябрь",
		"LOC_DEC": "Декабрь",
		"LOC_JAN": "Январь",
		"LOC_FEB": "Февраль",
		"LOC_MAR": "Март",
		"LOC_APR": "Апрель",
		"LOC_MAY": "Май",
		"LOC_JUN": "Июнь",
		"LOC_JUL": "Июль",
		"LOC_AUG": "Август",
		"LOC_INFO": "О вершине",
		"LOC_NODES": "Вершины",
		"LOC_EDGES": "Рёбра",
		"LOC_SETTINGS": "Настройки",
		"LOC_FILTERS": "Фильтры",
		
		"LOC_NO_SELECTED_NODE": "Кликните на вершину, чтобы получить информацию о ней",
		"LOC_INTERNAL_LINKS_FILTER": "Фильтр внутренних дуг:",
		"LOC_EXTERNAL_LINKS_FILTER": "Фильтр внешних дуг:",
		"LOC_NODE_THRESHOLD": "Все вершины:",
		"LOC_PASSIVETEXTALPHA": "Яркость невыделенных вершин:",
		"LOC_PASSIVEEDGEALPHA": "Яркость невыделенных рёбер:",
		"LOC_NODE_SIZE_TEXT": "Размер вершин: ",
		"LOC_LINK_SIZE_TEXT": "Размер ребер: ",
		"LOC_BUILD_LAYOUT": "Уложить граф",
		"LOC_NODEFONT": "Размер шрифта вершин:",
		"LOC_RINGFONT": "Размер шрифта круговой шкалы:",
		"LOC_SCENESIZE": "Размер сцены",
		"LOC_APPLY": "Применить",
		"LOC_ALL": "∀",
		"LOC_NONE": "∅",
		"LOC_VISIBLE": "Видимы",
		"LOC_SELECTED": "Выделены",
		"LOC_CHANGE": "Изменить",
		"LOC_GROUP": "Кластер",
		"LOC_COLOR": "Цвет",
		"LOC_ENTERGROUP": "Перейти к кластеру",
		"LOC_LEAVEGROUP": "Выйти из кластера",
		"LOC_LINKEDNODES": "Связанные вершины:",
		"LOC_STATSTUB": "Кликните на сектор диаграммы, для получения информации по соответствующему кластеру",
		"LOC_STATCAPTION": "Статистика по кластерам (число кластеров: ",
		"LOC_MALE": "мужчины",
		"LOC_FEMALE": "женщины",
		"LOC_EDUCATION_MIDDLE": "среднее образование",
		"LOC_EDUCATION_HIGH": "высшее образование",
		"LOC_NODE_DATA": "Данные вершины",
		"LOC_FIT_TO_SCREEN": "Вписать в экран",
		"LOC_SORT_BY_RING": "Отсортировать",
		"LOC_CALC_MODULARITY": "Модулярность",
		"LOC_RING_FILTER_ADD": "Добавить фильтр",
		"LOC_RING_FILTER_ARCS_GROUP": "Фильтровать дуги",
		"LOC_RING_FILTER_ARCS_GROUP_SINGLE": "Один конец (Shift+LMB)",
		"LOC_RING_FILTER_ARCS_GROUP_BOTH": "Оба конца (Alt+LMB)",
		"LOC_RING_PAINT_NODES": "Окрасить вершины",
		"LOC_FINDSTRING": "Найти по строке",
		"LOC_FINDREGEXP": "Найти по regexp",
		"LOC_NOT": "Не",
		"LOC_TREE": "Дерево",
		"LOC_SAVE_GRAPH": "Экспорт графа",
		"LOC_LOAD_GRAPH": "Импорт графа",
		"LOC_HELP": "Справка",
		"LOC_HELPLOC": "../css/help-ru.html",
		"LOC_GRAPHSTAT": "Статистика по графу:",
		"LOC_SUMWEIGHT": "∑ вес =",
		"LOC_ADDOPERAND": "Добавть операнд",
		"LOC_OPSUM": "Сумма",
		"#UNION": "Объединение",
		"#DIFF": "Разность",
		"#SYMDIFF": "Симметрическая разность",
		"#INTERSECT": "Пересечение",
		"LOC_CALCULATE": "Вычислить",
		"LOC_CLEANCALC": "Очистить",
		"LOC_STATECALCULATED": "Текущее состояние рассчитано калькулятором. Кликните, чтобы вернуться к предыдущему.",
    },
};
